version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

conda:
  environment: devtools/conda-envs/docs_env.yaml

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - method: pip
      path: modelforge-curate
    - method: pip
      path: modelforge-openmm