from typing import Dict, List, Tuple

import torch
import torch.nn as nn
from torch import Tensor

from loguru import logger as log

from modelforge.potential.utils import Dense

from modelforge.dataset.dataset import NNPInput
from modelforge.potential.neighbors import PairlistData

import math


class FukuiEquilibration(nn.Module):
    """
    Learns per-atom, per-channel Fukui weights and uses them to equilibrate the spin-up / spin-down monopole channels

    Parameters
    ---------
    number_of_per_atom_features : int
        Number of features per atom in the input embedding.
    hidden_dim : int, optional
        Number of hidden units in the MLP used to predict Fukui weights. Default is 32.
    """

    def __init__(self, number_of_per_atom_features: int, hidden_dim: int = 32):
        super().__init__()
        self.fukui_mlp = nn.Sequential(
            Dense(
                number_of_per_atom_features,
                hidden_dim,
                activation_function=nn.SiLU(),
            ),
            Dense(hidden_dim, 2),
        )
        self.softplus = nn.Softplus()

    @staticmethod
    def _per_system_sum(
        values: torch.Tensor,
        atomic_subsystem_indices: torch.Tensor,
        n_systems: int,
    ) -> torch.Tensor:

        # initialize an array of zeros for each system
        out = torch.zeros(
            n_systems, values.shape[-1], device=values.device, dtype=values.dtype
        )

        # sum them up
        out.index_add_(0, atomic_subsystem_indices, values)
        return out

    @staticmethod
    def equilibrate_channel(
        p: torch.Tensor,
        f_raw: torch.Tensor,
        target: torch.Tensor,
        atomic_subsystem_indices: torch.Tensor,
        n_systems: int,
    ) -> torch.Tensor:
        """
        Core Fukui-equilibration operation.

        Parameters
        ----------
        p : (n_atoms, 1) current per-atom monopole values for this channel
        f_raw : (n_atoms, 1) non-negative, un-normalized Fukui weights for
            this channel
        target : (n_systems, 1) target per-system sum for this channel
        """
        sums = FukuiEquilibration._per_system_sum(
            f_raw, atomic_subsystem_indices, n_systems
        )
        f_norm = f_raw / sums[atomic_subsystem_indices].clamp_min(1e-8)

        p_sum = FukuiEquilibration._per_system_sum(
            p, atomic_subsystem_indices, n_systems
        )
        residual = target - p_sum

        # distribute the extra charge based on the normalized weights
        return p + f_norm * residual[atomic_subsystem_indices]

    def forward(self, inputs: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        """
        Predicts Fukui weights from local atomic features only, then equilibrates both channels.
        """
        atomic_embedding = inputs["atomic_embedding"]
        p_up = inputs["per_atom_charge_up"]
        p_down = inputs["per_atom_charge_down"]
        atomic_subsystem_indices = inputs["atomic_subsystem_indices"]
        per_system_total_charge = inputs["per_system_total_charge"]
        per_system_spin_multiplicity = inputs["per_system_spin_multiplicity"]

        n_systems = (
            int(atomic_subsystem_indices.max().item()) + 1
            if atomic_subsystem_indices.numel() > 0
            else 0
        )
        # we want to make sure that we only have positive values so wrap with a soft plus
        raw_weights = self.softplus(self.fukui_mlp(atomic_embedding)) + 1e-6
        f_up_raw, f_down_raw = raw_weights[:, 0:1], raw_weights[:, 1:2]

        Q = per_system_total_charge.reshape(-1, 1).to(p_up.dtype)
        S = per_system_spin_multiplicity.reshape(-1, 1).to(p_up.dtype) - 1.0
        target_up = 0.5 * (Q + S)
        target_down = 0.5 * (Q - S)

        corrected_up = self.equilibrate_channel(
            p_up, f_up_raw, target_up, atomic_subsystem_indices, n_systems
        )
        corrected_down = self.equilibrate_channel(
            p_down, f_down_raw, target_down, atomic_subsystem_indices, n_systems
        )

        return {
            "per_atom_charge_up": corrected_up,
            "per_atom_charge_down": corrected_down,
        }


def spin_resolved_gaussian_smeared_potential(
    d_ij: torch.Tensor,
    idx: torch.Tensor,
    n_atoms: int,
    density: torch.Tensor,
    sigma: float,
) -> torch.Tensor:
    """
    This corresponds to eqn 16 in mace polar computing the spin resolved electrostatic potential.

    Parameters
    ----------
    d_ij : (n_atoms, 1) euclidian distance between interaction pairs
    idx : (n_atoms, 2) indices of interaction pairs
    n_atoms: number of atoms
    density : (n_atoms, 1) monopole density ( p_up or p_down)
    sigma : Gaussian smearing width

    Returns
    -------
    (n_atoms, 1) electrostatic potential generated by `density` at
    every atom, evaluated via Eq. 16-17 restricted to the monopole
    (l=0) term, including the self-interaction contribution.
    """

    idx_i = idx[0]
    idx_j = idx[1]

    # equation 37: monopole part of the sum in eqn 35
    kernel = torch.erf(d_ij / (math.sqrt(2.0) * sigma)) / d_ij
    pairwise_potential = torch.zeros(
        n_atoms, 1, device=density.device, dtype=density.dtype
    )

    pairwise_potential.scatter_add_(0, idx_i.unsqueeze(-1), kernel * density[idx_j])

    # we need to calculate what happens for r=0, i.e., self interactions
    # analytical limit for r->0 of the erf function above is  erf(r / (sqrt(2) sigma)) / r
    # paper suggests an "offset of 0.02 Angstroms" to avoid singularities, but we can just use the analytical limit instead
    # to avoid another cutoff masking, I think.
    self_coefficient = math.sqrt(2.0 / math.pi) / sigma
    self_term = self_coefficient * density

    return pairwise_potential + self_term


class LongRangeElectrostaticUpdate(nn.Module):
    """

    This module will perform the non-local updates.

    The init will construct the MLP that will take in the local atomic features, the current p_up and p_down,
    and the non-local potentials v_up and v_down they generate (Eqn. 19's embedding of non-local + local + current-density information).
    Forward function will perform the updates to p_up and p_down  and the up and down potentials.


    """

    def __init__(
        self,
        number_of_per_atom_features: int,
        electrostatic_smearing_width: float,
        hidden_dim: int = 64,
    ):
        """

        Parameters
        ----------
        number_of_per_atom_features : int
            Number of features per atom.
        electrostatic_smearing_width : float
            Width of the electrostatic smearing.
        hidden_dim : int, optional
            Dimension of the hidden layers in the MLP, by default 64.
        """
        super().__init__()
        self.smearing_width = electrostatic_smearing_width

        self.update_nonlocal_mlp = nn.Sequential(
            Dense(
                number_of_per_atom_features + 4,
                hidden_dim,
                activation_function=nn.SiLU(),
            ),
            Dense(hidden_dim, hidden_dim, activation_function=nn.SiLU()),
            Dense(hidden_dim, 4),  # add 4 for delta_p_up, delta_p_down, f_up, f_down
        )

        self.softplus = nn.Softplus()

    def forward(
        self,
        atomic_embedding: torch.Tensor,
        p_up: torch.Tensor,
        p_down: torch.Tensor,
        d_ij: torch.Tensor,
        idx: torch.Tensor,
        atomic_subsystem_indices: torch.Tensor,
        n_atoms: int,
        per_system_total_charge: torch.Tensor,
        per_system_spin_multiplicity: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:

        # First handle the non-local electrostatic features (Eqs. 16-17)

        v_up = spin_resolved_gaussian_smeared_potential(
            d_ij, idx, n_atoms, p_up, self.smearing_width
        )
        v_down = spin_resolved_gaussian_smeared_potential(
            d_ij, idx, n_atoms, p_down, self.smearing_width
        )

        # predict an additive update + new Fukui weights (Eqs. 18-24).
        # we will create a tensor that is the atomic embedding, p_up, p_down, v_up, and v_down
        features = torch.cat([atomic_embedding, p_up, p_down, v_up, v_down], dim=1)
        out = self.update_nonlocal_mlp(features)
        delta_p_up, delta_p_down, f_up_raw, f_down_raw = torch.split(
            out, [1, 1, 1, 1], dim=1
        )
        # make sure all positive
        f_up_raw = self.softplus(f_up_raw) + 1e-6
        f_down_raw = self.softplus(f_down_raw) + 1e-6

        # unequilibrated p_up p_down
        p_up_tilde = p_up + delta_p_up
        p_down_tilde = p_down + delta_p_down

        # Equilibrate the channels to recorrect
        n_systems = (
            int(atomic_subsystem_indices.max().item()) + 1
            if atomic_subsystem_indices.numel() > 0
            else 0
        )
        Q = per_system_total_charge.reshape(-1, 1).to(p_up.dtype)
        S = per_system_spin_multiplicity.reshape(-1, 1).to(p_up.dtype) - 1.0
        target_up = 0.5 * (Q + S)
        target_down = 0.5 * (Q - S)

        p_up_new = FukuiEquilibration.equilibrate_channel(
            p_up_tilde, f_up_raw, target_up, atomic_subsystem_indices, n_systems
        )
        p_down_new = FukuiEquilibration.equilibrate_channel(
            p_down_tilde, f_down_raw, target_down, atomic_subsystem_indices, n_systems
        )

        return p_up_new, p_down_new, v_up, v_down


class AimNet2SRCore(torch.nn.Module):

    # per-atom properties computed by the core from the equilibrated charge and
    # spin channels; readout heads must not overwrite them
    core_output_properties = frozenset(
        {
            "per_atom_scalar_representation",
            "per_atom_charge",
            "per_atom_charge_up",
            "per_atom_charge_down",
            "per_atom_spin_density",
            "per_atom_spin_multiplicity",
            "per_atom_electrostatic_energy",
        }
    )

    def __init__(
        self,
        featurization: Dict[str, Dict[str, int]],
        number_of_radial_basis_functions: int,
        number_of_vector_features: int,
        number_of_interaction_modules: int,
        interaction_module_hidden_layers: List[List[int]],
        output_module_hidden_layers: List[int],
        activation_function_parameter: Dict[str, str],
        predicted_properties: List[str],
        predicted_dim: List[int],
        maximum_interaction_radius: float,
        number_of_long_range_updates: int = 2,
        electrostatic_smearing_width: float = 0.1,
        electrostatic_maximum_interaction_radius=15.0,  # note this isn't used directly
    ) -> None:
        """
        Core architecture of the AimNet2SR (spin-resolved) model for molecular property
        prediction.

        This incorporates ideas from MACE-Polar regarding spin resolved charge density and long range updates.

        Parameters
        ----------
        featurization : Dict[str, Dict[str, int]]
            Configuration dictionary specifying feature details for atomic
            embeddings.
        number_of_radial_basis_functions : int
            Number of radial basis functions used in the radial symmetry
            function.
        number_of_vector_features : int
            Number of vector features used in the model, which determines the
            dimensionality of the angular symmetry functions.
        number_of_interaction_modules : int
            Number of interaction modules in the model, determining the depth of
            message passing.
        interaction_module_hidden_layers : List[List[int]]
            List of hidden layer sizes for each interaction module. Note, this requires at least one value to be defined
            as this specifies the output size of the first layer in the interaction module and input size of the final layer
        output_module_hidden_layers : List[int]
            List of hidden layer sizes for the output modules, which are used to
            compute the final predictions from the atomic embeddings.
        activation_function_parameter : Dict[str, str]
            Configuration of activation functions used across the model.
        predicted_properties : List[str]
            List of properties that the model is predicting (e.g., energy,
            forces).
        predicted_dim : List[int]
            The dimensionality of each predicted property.
        maximum_interaction_radius : float
            The cutoff radius for atomic interactions in the model.

        """

        super().__init__()

        log.debug("Initializing the AimNet2_SR (spin-resolved Fukui)  architecture.")
        self.model_name = "aimnet2_sr"
        self.activation_function = activation_function_parameter["activation_function"]

        # Initialize representation block
        self.representation_module = AimNet2SRRepresentation(
            maximum_interaction_radius,
            number_of_radial_basis_functions,
            featurization_config=featurization,
        )
        number_of_per_atom_features = int(
            featurization["atomic_number"]["number_of_per_atom_features"]
        )

        # scale by 1/sqrt(F_atom * G), the fan-in of the einsum contraction,
        # so vector features start on the same scale as radial features
        self.agh = nn.Parameter(
            torch.randn(
                number_of_per_atom_features,  # F_atom
                number_of_radial_basis_functions,  # G
                number_of_vector_features,  # H
            )
            / math.sqrt(number_of_per_atom_features * number_of_radial_basis_functions)
        )

        # Define interaction modules for message passing
        self.interaction_modules = torch.nn.ModuleList(
            [
                AimNet2SRInteractionModule(
                    number_of_per_atom_features=number_of_per_atom_features,
                    number_of_radial_basis_functions=number_of_radial_basis_functions,
                    number_of_vector_features=number_of_vector_features,
                    hidden_layers=interaction_module_hidden_layers[i],
                    activation_function=self.activation_function,
                    is_first_module=(i == 0),
                )
                for i in range(number_of_interaction_modules)
            ]
        )
        # Define output layers to calculate per-atom predictions
        overlap = self.core_output_properties.intersection(predicted_properties)
        if overlap:
            raise ValueError(
                f"predicted_properties {sorted(overlap)} are computed by the "
                "AimNet2SR core from the equilibrated charge and spin channels and "
                "will not be overwritten by a readout head. Remove them from "
                "predicted_properties; the core always returns them."
            )
        self.output_layers = nn.ModuleDict()
        for property, dim in zip(predicted_properties, predicted_dim):
            self.output_layers[property] = mlp_init(
                n_in_features=number_of_per_atom_features,
                n_out_features=int(dim),
                activation_function=self.activation_function,
                hidden_layers=output_module_hidden_layers,
            )

        self.fukui_equilibration = FukuiEquilibration(
            number_of_per_atom_features=number_of_per_atom_features
        )

        # non-local long-range polarizable field updates.
        self.electrostatic_smearing_width = electrostatic_smearing_width
        from openff.units import unit
        from modelforge.utils.units import GlobalUnitSystem

        self.coulomb_constant = (
            (
                unit.avogadro_constant
                * unit.elementary_charge**2
                / (4 * math.pi * unit.epsilon_0)
            )
            .to(
                GlobalUnitSystem.get_units("energy")
                * GlobalUnitSystem.get_units("length")
            )
            .m
        )
        self.long_range_updates = torch.nn.ModuleList(
            [
                LongRangeElectrostaticUpdate(
                    number_of_per_atom_features=number_of_per_atom_features,
                    electrostatic_smearing_width=electrostatic_smearing_width,
                )
                for _ in range(number_of_long_range_updates)
            ]
        )

        # from modelforge.potential.processing import CoulombPotential

        # note this will need to change when we switch to supporting multiple cutoffs
        # self.coulomb_potential = CoulombPotential(cutoff=maximum_interaction_radius)

    def compute_properties(
        self,
        data: NNPInput,
        pairlist: PairlistData,
        electrostatic_pairlist: PairlistData,
    ) -> Dict[str, torch.Tensor]:
        """
        Calculate the requested properties for a given input batch.

        Parameters
        ----------
        data : NNPInput
            The input data for the model.
        pairlist: PairlistData
            The output from the neighborlist module associated with the "local" cutoff.
        electrostatic_pairlist: PairlistData
            The output from the neighborlist module associated with the "electrostatic" cutoff.
        Returns
        -------
        Dict[str, torch.Tensor]
            The calculated per-atom scalar representations and atomic subsystem
            indices.
        """

        rep = self.representation_module(data, pairlist)
        atomic_embedding = rep["atomic_embedding"]
        r_ij, d_ij, f_ij, f_cutoff = (
            pairlist.r_ij,
            pairlist.d_ij,
            rep["f_ij"],
            rep["f_cutoff"],
        )
        # Scalar Gaussian expansion for radial terms
        gs = f_ij * f_cutoff  # Shape: (number_of_pairs, G)
        # Unit direction vectors
        u_ij = r_ij / d_ij
        # Compute gv with shape (number_of_pairs, 3, G)
        gv = u_ij.unsqueeze(-1) * gs.unsqueeze(1)  # Broadcasting over G

        # Atomic embedding "a" Eqn. (3)

        p_up = torch.zeros(
            (atomic_embedding.shape[0], 1),
            dtype=atomic_embedding.dtype,
            device=atomic_embedding.device,
        )
        p_down = torch.zeros(
            (atomic_embedding.shape[0], 1),
            dtype=atomic_embedding.dtype,
            device=atomic_embedding.device,
        )

        per_system_spin_multiplicity = data.per_system_spin_state

        # Perform message passing using interaction modules
        for i, interaction in enumerate(self.interaction_modules):

            delta_a, delta_p_up, delta_p_down, f = interaction(
                atomic_embedding,
                p_up,
                p_down,
                pairlist.pair_indices,
                gs,
                gv,
                self.agh,
            )

            # Update atomic embeddings
            atomic_embedding = atomic_embedding + delta_a

            scaled_delta_up = f * delta_p_up
            scaled_delta_down = f * delta_p_down

            # Update partial charges
            if i == 0:
                p_up = scaled_delta_up
                p_down = scaled_delta_down
            else:
                p_up = p_up + scaled_delta_up
                p_down = p_down + scaled_delta_down

        # according to the MACE polar paper, we just do the equilibration after we go through each of layers
        equilibrated = self.fukui_equilibration(
            {
                "atomic_embedding": atomic_embedding,
                "per_atom_charge_up": p_up,
                "per_atom_charge_down": p_down,
                "per_system_total_charge": data.per_system_total_charge.to(
                    dtype=atomic_embedding.dtype
                ),
                "per_system_spin_multiplicity": per_system_spin_multiplicity,
                "atomic_subsystem_indices": data.atomic_subsystem_indices.to(
                    dtype=torch.int64
                ),
            }
        )
        p_up = equilibrated["per_atom_charge_up"]
        p_down = equilibrated["per_atom_charge_down"]

        per_system_total_charge = data.per_system_total_charge.to(
            dtype=atomic_embedding.dtype
        )
        atomic_subsystem_indices = data.atomic_subsystem_indices.to(dtype=torch.int64)

        # stage 2 is the non-local polarizable field updates
        d_ij = electrostatic_pairlist.d_ij
        idx = electrostatic_pairlist.pair_indices

        n_atoms = data.positions.shape[0]
        for lr_update in self.long_range_updates:
            p_up, p_down, _, _ = lr_update(
                atomic_embedding,
                p_up,
                p_down,
                d_ij,
                idx,
                atomic_subsystem_indices,
                n_atoms,
                per_system_total_charge,
                per_system_spin_multiplicity,
            )

        # now use the updated p_up and p_down to get partial charges and partial spin density
        partial_charges = p_up + p_down
        partial_spin_density = p_up - p_down

        """
        Per-atom contribution to E_Hartree = 1/2 sum_ij p_i p_j T_ij
        (Eq. 35, monopole part), i.e. 0.5 * rho_i * v_i(rho), including the
        self-energy term. Summing this over all atoms in a system gives
        that system's non-local electrostatic ("Hartree") energy.
        
        # since this is just based upon partial charges at this point, can just implement this as 
        # a post processing option, similar to normal coulombic potential
        """
        per_atom_electrostatic_energy = (
            self.coulomb_constant
            * 0.5
            * partial_charges
            * spin_resolved_gaussian_smeared_potential(
                d_ij,
                idx,
                n_atoms,
                partial_charges,
                self.electrostatic_smearing_width,
            )
        )

        if torch.isnan(atomic_embedding).any():
            raise ValueError("NaN values detected in atomic embeddings.")
        if torch.isnan(partial_charges).any():
            raise ValueError("NaN values detected in partial charges.")
        if torch.isnan(partial_spin_density).any():
            raise ValueError("NaN values detected in partial spin density.")
        # if torch.isnan(per_atom_electrostatic_energy).any():
        #    raise ValueError("NaN values detected in per-atom electrostatic energy.")

        return {
            "per_atom_scalar_representation": atomic_embedding,
            "atomic_subsystem_indices": data.atomic_subsystem_indices,
            "atomic_numbers": data.atomic_numbers,
            "per_atom_charge": partial_charges,
            "per_atom_electrostatic_energy": per_atom_electrostatic_energy,
            "per_atom_spin_density": partial_spin_density,
            "per_atom_spin_multiplicity": partial_spin_density,
            "per_atom_charge_up": p_up,  # note sure we need to return this, but will for debugging now
            "per_atom_charge_down": p_down,
        }

    def forward(
        self,
        data: NNPInput,
        pairlist_output: PairlistData,
        electrostatic_pairlist_output: PairlistData,
    ) -> Dict[str, torch.Tensor]:
        """
        Implements the forward pass through the network.

        Parameters
        ----------
        data : NNPInput
            Contains input data for the batch obtained directly from the
            dataset, including atomic numbers, positions, and other relevant
            fields.
        pairlist_output : PairListData
            Contains the indices for the selected pairs and their associated
            distances and displacement vectors.
        electrostatic_pairlist_output: PairListData
            Contains the indices for the selected pairs and their associated
            distances and displacement vectors associated with the electrostatic cutoff


        Returns
        -------
        Dict[str, torch.Tensor]
            The calculated per-atom properties and other properties from the
            forward pass.
        """
        # perform the forward pass implemented in the subclass
        results = self.compute_properties(
            data, pairlist_output, electrostatic_pairlist_output
        )
        atomic_embedding = results["per_atom_scalar_representation"]

        # The way this is setup, we will always return per_atom_charge and per_atom_spin_density
        # as those come directly from the compute_properties method.

        # Compute all specified outputs
        for output_name, output_layer in self.output_layers.items():
            output = output_layer(atomic_embedding)
            results[output_name] = output

        return results


def mlp_init(
    n_in_features: int,
    n_out_features: int,
    activation_function: nn.Module,
    hidden_layers: List[int],
) -> nn.Sequential:
    """
    Helper function to create a sequence of dense layers with an activation function.


    Parameters
    ----------
    n_in_features : int
        Number of input features for the first layer.
    n_out_features : int
        Number of output features for the last layer.
    activation_function : nn.Module
        Activation function to be applied after each hidden layer.
    hidden_layers : List[int]
        List of integers specifying the number of features for each hidden layer.
        First element is the number of output features of the first layer,
        and the last element is the number of input features of the final layer.
        If only a single value is provided, it will be used as the output size of the first layer
        and input size of the final layer (no intermediate layers will be created).
    """

    # Single MLP producing combined outputs
    num_of_layers = len(hidden_layers)

    mlp = nn.Sequential()

    mlp.append(
        Dense(
            in_features=n_in_features,
            out_features=hidden_layers[0],
            activation_function=activation_function,
        )
    )
    for i in range(1, num_of_layers):
        mlp.append(
            Dense(
                in_features=hidden_layers[i - 1],
                out_features=hidden_layers[i],
                activation_function=activation_function,
            )
        )
    mlp.append(
        Dense(
            in_features=hidden_layers[-1],
            out_features=n_out_features,  # delta_q, f, delta_a
        )
    )
    return mlp


class AimNet2SRInteractionModule(nn.Module):
    def __init__(
        self,
        number_of_per_atom_features: int,
        number_of_radial_basis_functions: int,
        number_of_vector_features: int,
        hidden_layers: List[int],
        activation_function: nn.Module,
        is_first_module: bool = False,
    ):
        super().__init__()
        self.is_first_module = is_first_module
        self.number_of_per_atom_features = number_of_per_atom_features
        self.number_of_vector_features = number_of_vector_features
        self.gs_to_fatom = Dense(
            number_of_radial_basis_functions, number_of_per_atom_features, bias=False
        )

        if not self.is_first_module:
            self.number_of_input_features = (
                number_of_per_atom_features  # radial_contributions_emb
                + number_of_vector_features  # vector_contributions_emb
                + number_of_per_atom_features  # radial_contributions_up
                + number_of_vector_features  # vector_contributions_up
                + number_of_per_atom_features  # radial_contributions_down (new)
                + number_of_vector_features  # vector_contributions_down (new)
            )
        else:
            self.number_of_input_features = (
                number_of_per_atom_features  # radial_contributions_emb
                + number_of_vector_features  # vector_contributions_emb
            )

        # Single MLP producing combined outputs
        self.mlp = mlp_init(
            n_in_features=self.number_of_input_features,
            n_out_features=self.number_of_per_atom_features + 3,
            activation_function=activation_function,
            hidden_layers=hidden_layers,
        )

    def calculate_radial_contributions(
        self,
        gs: Tensor,
        a_j: Tensor,
        number_of_atoms: int,
        idx_i: Tensor,
    ) -> Tensor:
        """
        Compute radial contributions for each atom based on pair interactions.

        Parameters
        ----------
        gs : Tensor
            Radial symmetry functions with shape (number_of_pairs, G).
        a_j : Tensor
            Neighbour (atom j) features for each pair with shape (number_of_pairs, F_atom) or (number_of_pairs, 1).
        number_of_atoms : int
            Total number of atoms in the system.
        idx_i : Tensor
            Index of the central atom for each pair, with shape (number_of_pairs,).

        Returns
        -------
        Tensor
            Radial contributions aggregated per atom, with shape (number_of_atoms, F_atom).
        """
        # Map gs to shape (number_of_pairs, F_atom)
        mapped_gs = self.gs_to_fatom(gs)  # Shape: (number_of_pairs, F_atom)

        # Compute avf_s using element-wise multiplication
        avf_s = a_j * mapped_gs  # Shape: (number_of_pairs, F_atom)

        # Initialize tensor to accumulate radial contributions
        radial_contributions = torch.zeros(
            (number_of_atoms, avf_s.shape[-1]),
            device=avf_s.device,
            dtype=avf_s.dtype,
        )
        # Aggregate per atom
        radial_contributions.index_add_(0, idx_i, avf_s)

        return radial_contributions

    def calculate_vector_contributions(
        self,
        gv: Tensor,
        a_j: Tensor,
        idx_i: Tensor,
        agh: Tensor,
        number_of_atoms: int,
        device: torch.device,
    ) -> Tensor:
        """
        Compute vector (angular) contributions for each atom based on pair interactions.

        Parameters
        ----------
        gv : Tensor
            Vector symmetry functions with shape (number_of_pairs, 3, G).
        a_j : Tensor
            Neighbour (atom j) features for each pair with shape (number_of_pairs, F_atom).
        idx_i : Tensor
            Index of the central atom for each pair, with shape (number_of_pairs,).
        agh : Tensor
            Transformation tensor with shape (F_atom, G, H).
        number_of_atoms : int
            Total number of atoms in the system.
        device : torch.device
            The device to perform computations on.

        Returns
        -------
        Tensor
            Vector contributions aggregated per atom, with shape (number_of_atoms, H).
        """
        # Compute per-pair vector contributions
        # avf_v: (number_of_pairs, H, 3)
        avf_v = torch.einsum("pa, pdg, agh -> phd", a_j, gv, agh)

        # Initialize tensor to accumulate vector contributions per atom
        avf_v_sum = torch.zeros(
            (number_of_atoms, avf_v.shape[1], avf_v.shape[2]),
            device=device,
            dtype=avf_v.dtype,
        )
        # Aggregate per atom by summing the vectors
        avf_v_sum.index_add_(0, idx_i, avf_v)  # Shape: (number_of_atoms, H, 3)

        # Smoothed norm over the vector components: sqrt(|v|^2 + eps^2) - eps.
        # Rotation invariant, smooth at v = 0 (e.g., symmetric sites), with
        # curvature capped at 1/eps for stable force training.
        eps = 1e-4 # sits between the round-off at symmetric sites (~1e-8) and typical features (RMS about 0.24)
        vector_contributions = (
            torch.sqrt(avf_v_sum.pow(2).sum(dim=-1) + eps**2) - eps
        )  # Shape: (number_of_atoms, H)

        # raise an error if we have NaN values in the vector contribution as this will cause problems later on
        if torch.isnan(vector_contributions).any():
            raise ValueError("NaN values detected in vector contributions.")
        return vector_contributions

    def calculate_contributions(
        self,
        atomic_embedding: Tensor,
        pair_indices: Tensor,
        gs: Tensor,
        gv: Tensor,
        agh: Tensor,
        calculate_vector_contributions: bool,
    ) -> Tuple[Tensor, Tensor]:
        # central atom i = pair_indices[0] receives the sum over its
        # neighbours j = pair_indices[1], using the neighbours' features
        idx_i, idx_j = pair_indices[0], pair_indices[1]
        a_j = atomic_embedding[idx_j]  # Shape: (number_of_pairs, F_atom)

        radial_contributions = self.calculate_radial_contributions(
            gs,
            a_j,
            atomic_embedding.shape[0],
            idx_i,
        )

        if calculate_vector_contributions:
            vector_contributions = self.calculate_vector_contributions(
                gv,
                a_j,
                idx_i,
                agh,
                number_of_atoms=atomic_embedding.shape[0],
                device=atomic_embedding.device,
            )
        else:
            # Return zeros with shape (number_of_atoms, number_of_vector_features)
            vector_contributions = torch.zeros(
                (atomic_embedding.shape[0], self.number_of_vector_features),
                dtype=atomic_embedding.dtype,
                device=atomic_embedding.device,
            )

        return radial_contributions, vector_contributions

    def forward(
        self,
        atomic_embedding: Tensor,
        partial_charge_up: Tensor,
        partial_charge_down: Tensor,
        pair_indices: Tensor,
        gs: Tensor,
        gv: Tensor,
        agh: Tensor,
    ) -> Tuple[Tensor, Tensor, Tensor]:

        # Calculate contributions from embeddings
        radial_contributions_emb, vector_contributions_emb = (
            self.calculate_contributions(
                atomic_embedding,
                pair_indices,
                gs,
                gv,
                agh,
                calculate_vector_contributions=True,
            )
        )

        if not self.is_first_module:
            radial_contributions_up, vector_contributions_up = (
                self.calculate_contributions(
                    partial_charge_up,
                    pair_indices,
                    gs,
                    gv,
                    agh,
                    calculate_vector_contributions=False,
                )
            )
            # New: spin-down channel messages, computed exactly like the
            # spin-up (formerly "charge") messages -- both channels of the
            # spin-charge density propagate through the graph identically.
            radial_contributions_down, vector_contributions_down = (
                self.calculate_contributions(
                    partial_charge_down,
                    pair_indices,
                    gs,
                    gv,
                    agh,
                    calculate_vector_contributions=False,
                )
            )

            combined_message = torch.cat(
                [
                    radial_contributions_emb,
                    vector_contributions_emb,
                    radial_contributions_up,
                    vector_contributions_up,
                    radial_contributions_down,
                    vector_contributions_down,
                ],
                dim=1,
            )
        else:
            combined_message = torch.cat(
                [
                    radial_contributions_emb,  # (N, F_atom)
                    vector_contributions_emb,  # (N, H)
                ],
                dim=1,
            )

        # Pass combined message through single MLP
        out = self.mlp(combined_message)

        # Split the output tensor into delta_q, f, and delta_a
        delta_p_up, delta_p_down, f, delta_a = torch.split(
            out, [1, 1, 1, self.number_of_per_atom_features], dim=1
        )

        return delta_a, delta_p_up, delta_p_down, f


class AimNet2SRRepresentation(nn.Module):
    def __init__(
        self,
        radial_cutoff: float,
        number_of_radial_basis_functions: int,
        featurization_config: Dict[str, Dict[str, int]],
    ):
        """
        Initialize the AimNet2SR representation layer.

        Parameters
        ----------
        radial_cutoff : float
            The cutoff distance for the radial symmetry function in nanometer.
        number_of_radial_basis_functions : int
            Number of radial basis functions to use.
        featurization_config : Dict[str, Union[List[str], int]]
            Configuration for the featurization process.
        """
        super().__init__()

        self.radial_symmetry_function_module = self._setup_radial_symmetry_functions(
            radial_cutoff, number_of_radial_basis_functions
        )
        # Initialize cutoff module
        from modelforge.potential import CosineAttenuationFunction
        from modelforge.potential.featurization import FeaturizeInput

        self.featurize_input = FeaturizeInput(featurization_config)
        self.cutoff_module = CosineAttenuationFunction(radial_cutoff)

    def _setup_radial_symmetry_functions(
        self, radial_cutoff: float, number_of_radial_basis_functions: int
    ):
        from modelforge.potential import SchnetRadialBasisFunction

        radial_symmetry_function = SchnetRadialBasisFunction(
            number_of_radial_basis_functions=number_of_radial_basis_functions,
            max_distance=radial_cutoff,
            dtype=torch.float32,
        )
        return radial_symmetry_function

    def forward(
        self,
        data: NNPInput,
        pairlist_output: PairlistData,
    ) -> Dict[str, torch.Tensor]:
        """
        Generate the radial symmetry representation of the pairwise distances.

        Parameters
        ----------
        data : NNPInput
            The input data including atomic positions and numbers.
        pairlist_output : PairlistData
            Pairwise distances between atoms and pair indices.

        Returns
        -------
        Dict[str, torch.Tensor]
            The radial basis functions and atomic embeddings.
        """

        # Convert distances to radial basis functions
        f_ij = self.radial_symmetry_function_module(pairlist_output.d_ij)
        # Apply cutoff function to radial basis
        f_cutoff = self.cutoff_module(pairlist_output.d_ij)

        return {
            "f_ij": f_ij,
            "f_cutoff": f_cutoff,
            "atomic_embedding": self.featurize_input(
                data
            ),  # add per-atom properties and embedding
        }
