name: CI_modelforge_curate

on:
  # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
  # The cookiecutter uses the "--initial-branch" flag when it runs git-init
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "ref-toml"
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"


concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.10", "3.11"]
        include:
          - os: ubuntu-latest
            n_procs: auto
          - os: macOS-latest
            n_procs: 0

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/provision-with-micromamba
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
        if : matrix.os == 'ubuntu-latest'

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/test_env_mac.yaml
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
        if: matrix.os != 'ubuntu-latest'

      - name: Install package
        # conda setup requires this special shell
        run: |
          python -m pip install . --no-deps
          python -m pip install -e ./modelforge-curate --no-deps

          micromamba list


      - name: Run tests
        # conda setup requires this special shell
        run: |
          pytest -n ${{matrix.n_procs}} --dist loadgroup -v --cov=modelforge-curate --cov-report=xml --color=yes --durations=50 modelforge-curate/modelforge/curate/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ github.event != 'schedule' }}  # Don't upload results on scheduled runs
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
